
// THEME: green, blue, crimson, brown, violet

const ARR_LINKS = [
    { page: 'assessment',              theme: 'brown',    title: 'Ассессмент' },
    { page: 'js-task',                 theme: 'brown',    title: '🍕 Задачи' },
    { page: 'theory',                  theme: 'brown',    title: '📑 Теория' },
    null,
    { page: 'theory-patterns',         theme: 'brown',    title: '⚡️ Паттерны' },
    { page: 'theory-paradigms',        theme: 'brown',    title: '⚡️ Парадигмы' },
    { page: 'theory-algoritms',        theme: 'brown',    title: '⚡️ Алгоритмы' },
    { page: 'theory-data-structures',  theme: 'brown',    title: '⚡️ Структуры данных' },
    null,
    { page: 'js',                      theme: 'blue',     title: '🥑 JavaScript' },
    { page: 'js-class',                theme: 'blue',     title: '🥑 Классы' },
    { page: 'js-objects',              theme: 'blue',     title: '🥑 Объекты' },
    { page: 'js-async',                theme: 'blue',     title: '🍋 Асинхронность' },
    { page: 'js-network',              theme: 'blue',     title: '🍋 Сеть' },
    null,
    { page: 'js-web-api',              theme: 'blue',     title: '🥑 Web API' },
    { page: 'js-web-components',       theme: 'blue',     title: 'WebComponents' },
    { page: 'canvas',                  theme: 'blue',     title: 'Canvas' },
    null,
    { page: 'react-js',                theme: 'violet',   title: '💥 React.js' },
    { page: 'react-api',               theme: 'violet',   title: '💥 React API' },
    { page: 'react-hooks',             theme: 'violet',   title: '💥 React Hooks' },
    { page: 'redux',                   theme: 'violet',   title: '🍋 Redux' },
    { page: 'react-router',            theme: 'violet',   title: 'React Router' },
    null,
    { page: 'prop-types',              theme: 'violet',   title: 'PropTypes' },
    { page: 'formik',                  theme: 'violet',   title: 'Formik' },
    { page: 'reselect',                theme: 'violet',   title: 'Reselect' },
    { page: 'material-ui',             theme: 'violet',   title: 'Material-UI & JSS' },
    null,
    { page: 'vue-js',                  theme: 'green',    title: '🥥 Vue.js' },
    { page: 'vue-vuex',                theme: 'green',    title: 'Vuex' },
    { page: 'vue-router',              theme: 'green',    title: 'Vue Router' },
    { page: 'vue-cli',                 theme: 'green',    title: 'Vue CLI & Pluging' },
    null,
    { page: 'testing',                 theme: 'brown',    title: '📑 Тестирование' },
    { page: 'jest',                    theme: 'brown',    title: '🔰 Jest' },
    { page: 'enzyme',                  theme: 'brown',    title: '🔰 Enzyme + Jest' },
    { page: 'react-testing',           theme: 'brown',    title: '🍋 React Testing' },
    { page: 'cypress',                 theme: 'brown',    title: '🔰 Cypress' },
    null,
    { page: 'html',                    theme: 'green',    title: 'HTML' },
    { page: 'css',                     theme: 'green',    title: 'CSS' },
    { page: 'css-flexbox',             theme: 'green',    title: 'Flexbox' },
    { page: 'css-grid',                theme: 'green',    title: 'CSS Grid' },
    { page: 'svg',                     theme: 'green',    title: 'SVG' },
    { page: 'sass',                    theme: 'green',    title: 'Sass' },
    { page: 'bootstrap',               theme: 'green',    title: 'Bootstrap' },
    null,
    { page: 'git',                     theme: 'crimson',  title: '🥥 Git' },
    { page: 'typescript',              theme: 'crimson',  title: '🍋 TypeScript' },
    { page: 'flow',                    theme: 'crimson',  title: '🍋 Flow' },
    { page: 'webpack',                 theme: 'crimson',  title: '🥥 Webpack' },
    { page: 'gulp',                    theme: 'crimson',  title: 'Gulp & Parcel' },
    { page: 'npm',                     theme: 'crimson',  title: 'NPM & Yarn' },
    { page: 'ramda',                   theme: 'crimson',  title: 'Ramda' },
    null,
    { page: 'other',                   theme: 'brown',    title: 'Other' },
    { page: 'node-js',                 theme: 'brown',    title: 'Node.js' },
    { page: 'php',                     theme: 'brown',    title: 'PHP' },
    { page: 'python',                  theme: 'brown',    title: 'Python' },
    { page: 'mysql',                   theme: 'brown',    title: 'mySql' },
    { page: 'linux',                   theme: 'brown',    title: 'Linux' },
    { page: 'jquery',                  theme: 'brown',    title: 'jQuery' },
];
